import type { Level, Room, Prank } from './types';

const entryScare = (id: string, msg: string, dmg: number): Prank => ({
  id,
  type: 'creepy',
  triggerText: 'You enter the room...',
  scareText: msg,
  sanityDamage: dmg,
  duration: 3000,
});

export const levels: Level[] = [
  {
    id: 1,
    name: 'The Abandoned Wing',
    subtitle: 'Where shadows learn to walk',
    introNarrative: [
      'The air inside is thick — not with dust, but with memory.',
      'Eleanor Voss walked these halls three weeks ago. Her footsteps are still echoing.',
      'Find the keys. Unlock the deeper rooms. She left breadcrumbs — if you can find them before the house finds you.',
    ],
    exitNarrative: [
      'A passage opens beneath the bookshelf — stone stairs descending into darkness.',
      'Eleanor\'s handwriting is carved into the wall: "THE HOUSE IS ALIVE. IT EATS MEMORIES."',
      'You are not escaping. You are going deeper. And it wants you to.',
    ],
    startRoom: 'foyer',
    requiredKeys: 5,
    colorScheme: {
      primary: '#1a1a2e',
      accent: '#e94560',
      bg: '#0f0f1a',
      glow: '#e9456040',
    },
    rooms: {
      foyer: {
        id: 'foyer',
        name: 'Grand Foyer',
        description: 'The entrance hall stretches before you, its chandelier swinging despite the still air. Dust motes dance in moonlight that filters through cracked windows. The wallpaper peels in long strips, revealing darker stains beneath.',
        atmosphere: 'eerie',
        exits: ['hallway', 'dining_room', 'library', 'smoking_lounge'],
        hasKey: false,
        prank: entryScare('foyer_entry', 'The front door SLAMS behind you. You are not leaving the way you came. A whisper from the chandelier: "Welcome home."', 18),
        items: ['old photograph'],
        ambientDescription: 'A distant creak echoes from upstairs.',
      },
      hallway: {
        id: 'hallway',
        name: 'Long Hallway',
        description: 'Portraits line the walls, their eyes seemingly following your every move. The carpet is worn and stained with something darker than wine. At the far end, a door stands slightly ajar.',
        atmosphere: 'eerie',
        exits: ['foyer', 'upstairs_landing', 'servant_quarters', 'coat_room'],
        hasKey: true,
        prank: {
          id: 'portrait_eyes',
          type: 'illusion',
          triggerText: 'You study the portraits more closely...',
          scareText: 'Every single portrait has turned to face you directly. Their painted eyes are wide open, and their mouths are frozen in silent screams. One portrait is of YOU — painted in a style centuries old.',
          sanityDamage: 22,
          duration: 3500,
        },
        items: [],
        ambientDescription: 'The carpet squelches under your feet.',
      },
      dining_room: {
        id: 'dining_room',
        name: 'Dining Room',
        description: 'A long table is set for a feast that never happened. Silver platters sit under covered dishes. The candles are melted to stubs, yet one still flickers. A chandelier hangs at a dangerous angle.',
        atmosphere: 'eerie',
        exits: ['foyer', 'kitchen', 'butler_pantry', 'wine_closet'],
        hasKey: true,
        prank: {
          id: 'dining_ghost',
          type: 'jumpscare',
          triggerText: 'You lift one of the silver covers...',
          scareText: 'Beneath every cover is a severed porcelain doll head. They all blink at you simultaneously. The chairs pull themselves out — someone is sitting down. You can\'t see them, but you can hear them chewing.',
          sanityDamage: 25,
          duration: 4000,
        },
        items: ['silver candlestick'],
        ambientDescription: 'You hear the faint clink of silverware and chewing.',
      },
      library: {
        id: 'library',
        name: 'The Library',
        description: 'Floor-to-ceiling bookshelves dominate the room. Books lie scattered on the floor, some open to pages covered in red ink. A reading chair faces the fireplace, which emits a faint blue glow.',
        atmosphere: 'dread',
        exits: ['foyer', 'secret_passage', 'study', 'map_room'],
        hasKey: true,
        prank: {
          id: 'library_whisper',
          type: 'whisper',
          triggerText: 'You approach the reading chair...',
          scareText: '"GET OUT" — The whisper comes from everywhere and nowhere. Every book on the shelves slams shut simultaneously. The fireplace goes dark. In its dying embers, you see a face — YOUR face — staring back, mouthing "too late."',
          sanityDamage: 28,
          duration: 4000,
        },
        items: ['tome of rituals'],
        ambientDescription: 'Pages turn by themselves in the corner.',
        journalEntry: { id: 'journal_eleanor_1', title: "Eleanor's Notebook — Entry 1", text: "Day 3. The library books rewrite themselves when I'm not looking. I found one that describes ME — my childhood, my degrees, my fears. It knows more about me than I do. It's reading me like a book. I am the book.", chapter: 1 },
      },
      kitchen: {
        id: 'kitchen',
        name: 'Kitchen',
        description: 'Rusted pots hang from hooks above an ancient stove. The sink drips a dark liquid. Cabinet doors hang open revealing nothing but darkness inside. A narrow service door leads somewhere dark.',
        atmosphere: 'eerie',
        exits: ['dining_room', 'pantry', 'scullery'],
        hasKey: false,
        prank: {
          id: 'kitchen_slam',
          type: 'door_slam',
          triggerText: 'You reach for the cabinet doors...',
          scareText: 'Every cabinet door SLAMS shut with deafening force. The stove burners ignite — blue flames that form the shape of grasping hands. The word "STAY" burns itself into the wall above the stove.',
          sanityDamage: 24,
          duration: 3500,
        },
        items: ['rusty knife'],
        ambientDescription: 'The faucet drips something thick and dark.',
      },
      pantry: {
        id: 'pantry',
        name: 'Dark Pantry',
        description: 'Shelves are stocked with jars containing things you cannot identify. The air is thick and sweet with decay. A small window is boarded up from the outside.',
        atmosphere: 'dread',
        exits: ['kitchen'],
        hasKey: false,
        prank: entryScare('pantry_jars', 'The jars begin to tremble on their shelves. One shatters — inside is a tiny hand, still moving. The other jars crack, one by one, in sequence, moving toward you.', 20),
        items: ['strange herb'],
        ambientDescription: 'Something inside a jar is moving.',
      },
      servant_quarters: {
        id: 'servant_quarters',
        name: 'Servant Quarters',
        description: 'Narrow beds line the walls, their sheets stained and tangled. A child\'s doll sits propped on a pillow, its head turned backward. Small handprints smear the walls above the beds.',
        atmosphere: 'dread',
        exits: ['hallway', 'laundry_room'],
        hasKey: false,
        prank: {
          id: 'servant_mirror',
          type: 'mirror',
          triggerText: 'You look into the cracked mirror...',
          scareText: 'Your reflection smiles back at you — but you are not smiling. It raises a finger to its lips, then reaches through the glass. You feel its cold fingers ON your face. The other beds\' sheets begin to bulge upward, one by one.',
          sanityDamage: 30,
          duration: 4500,
        },
        items: ['room key fragment'],
        ambientDescription: 'A child giggles somewhere nearby, getting closer.',
      },
      upstairs_landing: {
        id: 'upstairs_landing',
        name: 'Upstairs Landing',
        description: 'The staircase groans under your weight. At the top, a long corridor stretches into darkness. Doors line both sides, some hanging off hinges. The air is noticeably colder here.',
        atmosphere: 'dread',
        exits: ['hallway', 'nursery', 'master_bedroom'],
        hasKey: false,
        prank: {
          id: 'landing_shadow',
          type: 'shadow',
          triggerText: 'You step onto the landing...',
          scareText: 'Your shadow detaches from you and walks to the end of the corridor on its own. It turns back to face you, gesturing for you to follow. Then it opens a door and steps through. The door slams. You hear it lock from the other side.',
          sanityDamage: 26,
          duration: 4000,
        },
        items: [],
        ambientDescription: 'Your breath is visible. Something else is breathing too.',
      },
      secret_passage: {
        id: 'secret_passage',
        name: 'Secret Passage',
        description: 'Behind the bookshelf, a narrow stone passage descends into the foundation of the mansion. Water drips from above, and the walls are covered in scratch marks — long, desperate gouges in the stone. Some have dried blood.',
        atmosphere: 'terror',
        exits: ['library', 'cellar_preview'],
        hasKey: true,
        prank: {
          id: 'passage_hands',
          type: 'jumpscare',
          triggerText: 'You descend deeper into the passage...',
          scareText: 'PALE HANDS burst from the walls on both sides, grabbing at your arms, your hair, your throat! They pull and claw for an agonizing moment — then all vanish. Only deep scratch marks on your skin remain, and the sound of hands retreating into stone.',
          sanityDamage: 32,
          duration: 3000,
        },
        items: ['ancient key'],
        ambientDescription: 'Something is breathing in the dark below. It knows you\'re here.',
        journalEntry: { id: 'journal_eleanor_3', title: "Eleanor's Notebook — Entry 3", text: "Day 9. The passage behind the bookshelf goes deeper than the cellar. The walls have scratches — fingernail marks. Some are old. Some aren't. One set matches my handwriting: I carved my own name into the stone without remembering it.", chapter: 1 },
      },
      smoking_lounge: {
        id: 'smoking_lounge',
        name: 'Smoking Lounge',
        description: 'Leather chairs circle a cold fireplace. Cigar butts overflow from crystal ashtrays. The air still carries the ghost of tobacco smoke, and on the mantle, a clock runs backwards.',
        atmosphere: 'eerie',
        exits: ['foyer', 'billiard_room'],
        hasKey: false,
        prank: {
          id: 'smoke_figure',
          type: 'illusion',
          triggerText: 'You breathe in the old smoke...',
          scareText: 'The smoke coalesces into a figure sitting across from you. It has no face — just smooth skin. It tilts its head, then its face SPLITS open vertically, revealing rows of teeth going back infinitely. It speaks from inside: "Have a seat. Stay a while. Stay forever."',
          sanityDamage: 26,
          duration: 3500,
        },
        items: ['cigar box'],
        ambientDescription: 'The backwards clock ticks in reverse, counting down to something.',
      },
      coat_room: {
        id: 'coat_room',
        name: 'Coat Room',
        description: 'Coats hang from hooks, swaying gently as if someone just brushed past them. One coat is still warm to the touch. Small shoes are arranged neatly beneath, all pointing toward the back wall.',
        atmosphere: 'eerie',
        exits: ['hallway'],
        hasKey: false,
        prank: entryScare('coat_grab', 'A hand reaches from inside a coat and grabs your wrist. The coat falls to the floor — empty. The handprint on your wrist burns cold, and you can still feel fingers where there are none.', 20),
        items: ['brass button'],
        ambientDescription: 'The coats sway without any breeze. One just moved.',
      },
      study: {
        id: 'study',
        name: 'The Study',
        description: 'A massive oak desk dominates the room, covered in yellowed papers written in an unknown script. A globe sits in the corner, its continents all wrong. The desk chair faces the door — someone was watching for visitors.',
        atmosphere: 'dread',
        exits: ['library'],
        hasKey: true,
        prank: {
          id: 'study_globe',
          type: 'possession',
          triggerText: 'You spin the globe...',
          scareText: 'The globe stops on a landmass that isn\'t on any map. It rises from the globe — a miniature continent of flesh and teeth, pulsing. It opens a mouth and whispers your name, then your mother\'s name, then a name you don\'t recognize but somehow know is YOURS — from before.',
          sanityDamage: 30,
          duration: 4000,
        },
        items: ['magnifying glass'],
        ambientDescription: 'The papers on the desk rustle. Words are rewriting themselves.',
      },
      map_room: {
        id: 'map_room',
        name: 'Map Room',
        description: 'Maps cover every wall — floor plans of the mansion, but each one shows a different layout. In some versions, rooms exist that you\'ve never seen. In others, rooms you\'ve visited are simply missing.',
        atmosphere: 'dread',
        exits: ['library'],
        hasKey: false,
        prank: {
          id: 'map_change',
          type: 'illusion',
          triggerText: 'You study the floor plans closely...',
          scareText: 'You find a map with a room labeled "YOU ARE HERE." The dot moves in real time. Another dot — labeled "IT" — follows your path, one room behind. A third dot appears. A fourth. They\'re all following you. The map shows more dots appearing. Dozens. All heading to your room.',
          sanityDamage: 25,
          duration: 3500,
        },
        items: ['floor plan sketch'],
        ambientDescription: 'The maps seem to update when you look away. New rooms keep appearing.',
      },
      butler_pantry: {
        id: 'butler_pantry',
        name: 'Butler\'s Pantry',
        description: 'Silver polish stains line the shelves alongside tarnished serving pieces. A butler\'s uniform hangs on a hook, perfectly pressed — and still damp. The sleeves are too long, as if made for arms that don\'t bend.',
        atmosphere: 'eerie',
        exits: ['dining_room'],
        hasKey: false,
        prank: entryScare('butler_uniform', 'The uniform twitches. The sleeves inflate as if arms are inside — arms that bend in too many places. It steps off the hook and stands in the corner, facing the wall. It begins humming a funeral march.', 22),
        items: ['silver polish'],
        ambientDescription: 'The uniform sways. The sleeves just moved.',
      },
      wine_closet: {
        id: 'wine_closet',
        name: 'Wine Closet',
        description: 'A small, temperature-controlled closet with wooden racks. The bottles are all empty, their corks popped. One bottle has a note inside. It reads: "She preferred the red. She always preferred the red."',
        atmosphere: 'eerie',
        exits: ['dining_room'],
        hasKey: false,
        prank: entryScare('wine_flood', 'Wine — or what you pray is wine — begins flowing from the empty bottles. It pools on the floor and rises. In the rising liquid, you see faces — dozens of them — mouths open, drowning, reaching up toward you.', 22),
        items: ['empty wine bottle'],
        ambientDescription: 'A cork pops. Then another. The bottles are refilling.',
      },
      scullery: {
        id: 'scullery',
        name: 'Scullery',
        description: 'A narrow room with a deep stone sink stained with something that was never dishwater. Broken plates are stacked in a corner, each one cracked cleanly in half. A drain gurgles with a rhythm.',
        atmosphere: 'dread',
        exits: ['kitchen'],
        hasKey: false,
        prank: {
          id: 'scullery_drain',
          type: 'whisper',
          triggerText: 'You lean over the gurgling drain...',
          scareText: 'The gurgling resolves into words: "Let me up. I\'ve been so good. LET ME UP." Fingers emerge from the drain — too many fingers, too many joints. They grab the edge and PULL. A head begins to emerge. You see its eye. It sees you. It smiles.',
          sanityDamage: 28,
          duration: 4000,
        },
        items: ['broken plate shard'],
        ambientDescription: 'The drain gurgles like speech. It knows your name.',
      },
      laundry_room: {
        id: 'laundry_room',
        name: 'Laundry Room',
        description: 'A wringer washer sits dormant, but the water inside is still spinning. Lines hang with sheets that are already dry but swaying. Under one sheet, a shape stands perfectly still, pretending not to breathe.',
        atmosphere: 'dread',
        exits: ['servant_quarters'],
        hasKey: true,
        prank: {
          id: 'laundry_figure',
          type: 'shadow',
          triggerText: 'You pull back the sheet...',
          scareText: 'Nothing is behind the sheet — but your shadow has split in two. The new shadow stands apart from you, turning its head slowly. It won\'t leave. It follows with its own movements. When you raise your hand, it doesn\'t. It just watches.',
          sanityDamage: 28,
          duration: 4000,
        },
        items: [],
        ambientDescription: 'The sheet sways even though the air is dead. The shape moved.',
      },
      nursery: {
        id: 'nursery',
        name: 'The Nursery',
        description: 'A crib sits in the center, its mobile still turning with no wind. Toys are arranged in a perfect circle on the floor, all facing inward as if in worship. The walls are painted with a mural of a family — but the parents have been scratched out.',
        atmosphere: 'dread',
        exits: ['upstairs_landing', 'playroom'],
        hasKey: true,
        prank: {
          id: 'nursery_mobile',
          type: 'possession',
          triggerText: 'You touch the mobile...',
          scareText: 'The mobile stops. Every toy on the floor turns to face you. The crib mattress depresses. A lullaby begins — the one from YOUR childhood, but the words are wrong: "Hush little baby, don\'t say a word. Mama\'s gonna buy you a mockingbird. And if that bird don\'t sing, Mama\'s gonna make it SCREAM."',
          sanityDamage: 30,
          duration: 4500,
        },
        items: ['music box cylinder'],
        ambientDescription: 'The mobile turns without wind. The toys are closer than before.',
        journalEntry: { id: 'journal_eleanor_2', title: "Eleanor's Notebook — Entry 2", text: "Day 6. I found the nursery. The lullaby is real — it plays from nowhere. But the lyrics are wrong. They keep changing to reference my mother. My mother who died when I was seven. The house shouldn't know that. Nothing should know that.", chapter: 1 },
      },
      master_bedroom: {
        id: 'master_bedroom',
        name: 'Master Bedroom',
        description: 'A four-poster bed dominates the room, its curtains drawn. A vanity mirror faces the bed, reflecting nothing — the bed is empty in the mirror too, but the sheets are arranged differently. A wardrobe stands slightly open, darkness pooling at its base.',
        atmosphere: 'dread',
        exits: ['upstairs_landing', 'dressing_room'],
        hasKey: false,
        prank: {
          id: 'bedroom_mirror',
          type: 'mirror',
          triggerText: 'You open the bed curtains...',
          scareText: 'The bed is empty. But in the vanity mirror, someone lies in the bed watching you with hollow eyes. They sit up and reach through the mirror. Their hand presses against the glass from the other side — and the glass begins to bend outward toward you. It\'s going to break through.',
          sanityDamage: 32,
          duration: 4500,
        },
        items: ['locket'],
        ambientDescription: 'The vanity mirror reflects at a slight delay. Something moved in it.',
      },
      cellar_preview: {
        id: 'cellar_preview',
        name: 'Cellar Stairway',
        description: 'The passage opens onto steep stairs descending into the foundation. The walls weep moisture, and the air grows colder with each step. A faint red glow pulses from below. This leads deeper — to the next level.',
        atmosphere: 'terror',
        exits: ['secret_passage'],
        hasKey: false,
        prank: entryScare('cellar_breath', 'As you descend, you feel breath on the back of your neck — warm and wet. Not from above. From BELOW. Something in the cellar is breathing UPWARD, and it just exhaled on you.', 24),
        items: [],
        ambientDescription: 'The red glow below pulses like a heartbeat. YOUR heartbeat.',
      },
      billiard_room: {
        id: 'billiard_room',
        name: 'Billiard Room',
        description: 'A green felt table sits under a broken lamp. The balls are arranged in a perfect triangle, untouched. One cue stands upright in the corner, its tip stained red.',
        atmosphere: 'eerie',
        exits: ['smoking_lounge'],
        hasKey: false,
        prank: {
          id: 'billiard_shot',
          type: 'door_slam',
          triggerText: 'You lean over the table...',
          scareText: 'The balls break on their own with violent force. They don\'t scatter randomly — they roll into formation spelling "YOU DIE HERE." The cue swings like a pendulum and the lamp EXPLODES, showering you with glass.',
          sanityDamage: 24,
          duration: 3000,
        },
        items: ['chalk cube'],
        ambientDescription: 'The balls vibrate slightly. One just moved on its own.',
      },
      playroom: {
        id: 'playroom',
        name: 'Playroom',
        description: 'Blocks are stacked into a tower that reaches the ceiling. Board games are set up mid-play, pieces in positions that suggest the players simply vanished. A rocking horse rocks without a rider, without being touched.',
        atmosphere: 'dread',
        exits: ['nursery', 'toy_closet'],
        hasKey: false,
        prank: {
          id: 'playroom_blocks',
          type: 'creepy',
          triggerText: 'You touch the block tower...',
          scareText: 'The blocks rearrange. They spell your name. Then your birthday. Then the date you entered the mansion. Then TOMORROW\'S DATE. A child\'s voice: "Wanna play forever and ever and ever?" The rocking horse accelerates.',
          sanityDamage: 25,
          duration: 3500,
        },
        items: ['wooden block'],
        ambientDescription: 'The rocking horse never stops. It\'s getting faster.',
      },
      toy_closet: {
        id: 'toy_closet',
        name: 'Toy Closet',
        description: 'Shelves are crammed with toys from different eras — Victorian porcelain, 1950s tin robots, modern plush. All of them face the door. In the back, a jack-in-the-box sits with its lid slightly open, something pressing from inside.',
        atmosphere: 'terror',
        exits: ['playroom'],
        hasKey: false,
        prank: {
          id: 'jack_box',
          type: 'jumpscare',
          triggerText: 'You open the jack-in-the-box...',
          scareText: 'The lid BURSTS open — not a clown inside, but a tiny perfect model of the mansion. Inside the model, a tiny YOU looks up from the foyer. You watch yourself look up at yourself. The model contains a model that contains a model. Infinite recursion. The music is SCREAMING.',
          sanityDamage: 35,
          duration: 4000,
        },
        items: ['tin soldier'],
        ambientDescription: 'The jack-in-the-box lid strains against something inside. It wants out.',
      },
      dressing_room: {
        id: 'dressing_room',
        name: 'Dressing Room',
        description: 'Mannequins stand in poses that suggest conversation. Some wear dresses, others just wigs. Their hands are positioned as if holding invisible objects. One faces the corner — its posture suggests shame.',
        atmosphere: 'dread',
        exits: ['master_bedroom'],
        hasKey: false,
        prank: {
          id: 'mannequin_move',
          type: 'shadow',
          triggerText: 'You examine the mannequin facing the corner...',
          scareText: 'You turn it around. It has no face — just smooth skin. A face PUSHES outward from inside, features pressing through like fingers through cloth. It opens its new eyes and smiles with too many teeth: "Thank you for turning me around. I was so lonely facing the wall."',
          sanityDamage: 32,
          duration: 4500,
        },
        items: ['silk glove'],
        ambientDescription: 'The mannequins change position when you\'re not looking. One is closer now.',
      },
    },
  },
  {
    id: 2,
    name: 'The Cursed Cellar',
    subtitle: 'Where the foundation breathes',
    introNarrative: [
      'The cellar stairs descend into suffocating cold.',
      'This is where they found the first officer — sitting in the corner, catatonic, repeating one word: "Hungry."',
      'Eleanor\'s second note is pinned to the wall with a rusted nail: "IT BUILDS ITSELF FROM WHO ENTERS. WE ARE THE BRICKS."',
    ],
    exitNarrative: [
      'The well at the bottom reflects a ceiling that isn\'t there — it shows the attic above.',
      'The mansion is folded in on itself. The way down is the way up. The way out is the way in.',
      'Eleanor\'s third note floats in the well water: "I AM THE WALLS NOW. PLEASE DON\'T FOLLOW ME."',
    ],
    startRoom: 'cellar_stairs',
    requiredKeys: 5,
    colorScheme: {
      primary: '#1a0a0a',
      accent: '#ff4444',
      bg: '#0a0505',
      glow: '#ff444440',
    },
    rooms: {
      cellar_stairs: {
        id: 'cellar_stairs',
        name: 'Cellar Stairs',
        description: 'The stairs descend into suffocating darkness. Each step is slick with moisture. The walls narrow as you go down, and the temperature drops sharply. You can hear water dripping below.',
        atmosphere: 'dread',
        exits: ['wine_vault', 'boiler_room', 'tunnel'],
        hasKey: false,
        prank: entryScare('cellar_entry', 'The stairs collapse behind you. Not physically — you can still see them. But you know, with absolute certainty, that you cannot climb back up. Something fundamental has changed. You are deeper now, and the surface is further than it was.', 25),
        items: [],
        ambientDescription: 'The stairs creak with each step, as if something follows.',
      },
      wine_vault: {
        id: 'wine_vault',
        name: 'Wine Vault',
        description: 'Massive oak barrels line the walls, their contents long since turned to vinegar — or something worse. One barrel has split open, leaking a thick dark substance that moves against gravity.',
        atmosphere: 'dread',
        exits: ['cellar_stairs', 'alcove', 'tasting_room'],
        hasKey: true,
        prank: {
          id: 'wine_blood',
          type: 'jumpscare',
          triggerText: 'You touch the leaking substance...',
          scareText: 'It\'s warm. It\'s blood. ALL the barrels split open, flooding the floor with dark crimson that rises to your ankles. In the blood, you see dozens of reflections — yours, but from different ages. A child. A teenager. An elder. All of them drowning.',
          sanityDamage: 30,
          duration: 4000,
        },
        items: ['corkscrew'],
        ambientDescription: 'The liquid from the barrels pulses. It\'s flowing toward you.',
      },
      boiler_room: {
        id: 'boiler_room',
        name: 'Boiler Room',
        description: 'A massive rusted boiler dominates the room, pipes extending from it like veins. Despite being cold to the touch, you can feel a heartbeat within the metal. The pressure gauge spins wildly.',
        atmosphere: 'terror',
        exits: ['cellar_stairs', 'maintenance_tunnel', 'coal_chute'],
        hasKey: true,
        prank: {
          id: 'boiler_heart',
          type: 'possession',
          triggerText: 'You place your hand on the boiler...',
          scareText: 'The boiler PULSES — a living heartbeat. The metal splits open, revealing a pulsating mass of flesh and bone fused into the machinery. It opens a single eye. Then another. Then a hundred. They ALL stare at you. A mouth forms: "I\'ve been running on YOUR heartbeats."',
          sanityDamage: 38,
          duration: 4500,
        },
        items: [],
        ambientDescription: 'The boiler ticks like a metronome counting down to zero.',
      },
      tunnel: {
        id: 'tunnel',
        name: 'Collapsed Tunnel',
        description: 'A tunnel extends into the earth, partially collapsed. Through the rubble, you can see it continues deeper. Bones are visible in the exposed earth of the walls. Some of them look fresh.',
        atmosphere: 'terror',
        exits: ['cellar_stairs', 'crypt_entrance', 'bone_chamber'],
        hasKey: false,
        prank: {
          id: 'tunnel_bones',
          type: 'jumpscare',
          triggerText: 'You push through the rubble...',
          scareText: 'A SKULL rolls out and stops at your feet, facing up. Its jaw moves: "You\'re in MY house now." Bones rain from the ceiling — hundreds of them — clicking and clacking, forming a circle around you. The skulls all face inward. At you.',
          sanityDamage: 32,
          duration: 3500,
        },
        items: ['bone fragment'],
        ambientDescription: 'The bones in the walls shift when you look away. Some just moved closer.',
      },
      alcove: {
        id: 'alcove',
        name: 'Hidden Alcove',
        description: 'Behind the wine barrels, a small alcove contains an altar. Candles burn with black flames. Symbols are carved into every surface, and a book lies open on the altar, its pages moving on their own.',
        atmosphere: 'terror',
        exits: ['wine_vault'],
        hasKey: true,
        prank: {
          id: 'altar_book',
          type: 'possession',
          triggerText: 'You read from the open book...',
          scareText: 'The words rearrange into YOUR NAME, repeated endlessly. The black flames surge. Shadowy figures appear around the altar, chanting your name. Your mouth opens without your consent and you HEAR yourself chanting along. You can\'t stop your own voice.',
          sanityDamage: 40,
          duration: 5000,
        },
        items: ['ritual dagger'],
        ambientDescription: 'The black flames cast no light but burn your eyes. The book turns pages faster.',
        journalEntry: { id: 'journal_eleanor_4', title: "Eleanor's Notebook — Entry 4", text: "Day 11. Found the altar. The black flames cast shadows that move independently. I read from the book — I couldn't stop myself. My voice said things my mind didn't think. The house speaks through you if you let it. Maybe even if you don't.", chapter: 2 },
      },
      maintenance_tunnel: {
        id: 'maintenance_tunnel',
        name: 'Maintenance Tunnel',
        description: 'A claustrophobic tunnel with exposed pipes and electrical wiring. The wiring sparks intermittently, briefly illuminating scratches on the walls — five parallel lines, like claw marks. Fresh claw marks.',
        atmosphere: 'terror',
        exits: ['boiler_room', 'generator_room'],
        hasKey: false,
        prank: {
          id: 'tunnel_spark',
          type: 'shadow',
          triggerText: 'The lights flicker violently...',
          scareText: 'In the flash of sparks, a figure at the end of the tunnel — impossibly tall, arms dragging on the ground, head bent at an unnatural angle. Each flash brings it closer. The next flash — it\'s IN THE TUNNEL WITH YOU. The lights die. You feel it breathing.',
          sanityDamage: 35,
          duration: 4000,
        },
        items: ['fuse'],
        ambientDescription: 'The wiring sparks rhythmically. Something is making it spark.',
      },
      crypt_entrance: {
        id: 'crypt_entrance',
        name: 'Crypt Entrance',
        description: 'The tunnel opens into a stone chamber with an iron gate. Beyond the gate, rows of burial niches line the walls. The gate is old but sturdy. A feeling of profound wrongness emanates from within.',
        atmosphere: 'nightmare',
        exits: ['tunnel', 'crypt_main', 'urn_hall'],
        hasKey: false,
        prank: entryScare('crypt_cold', 'The temperature drops below freezing. Your breath crystallizes. Frost forms on your skin, and in the frost patterns on your arms, you see words: "WE HAVE BEEN WAITING." The frost burns.', 26),
        items: ['iron key'],
        ambientDescription: 'The air tastes like copper and old earth. Something exhaled on you.',
      },
      tasting_room: {
        id: 'tasting_room',
        name: 'Tasting Room',
        description: 'A small elegant room behind the vault, incongruously refined. A table is set with crystal glasses, each filled with a different colored liquid. Chairs are pulled out as if guests just excused themselves. The fireplace is lit with green flames.',
        atmosphere: 'dread',
        exits: ['wine_vault'],
        hasKey: false,
        prank: {
          id: 'tasting_toast',
          type: 'whisper',
          triggerText: 'You lift one of the crystal glasses...',
          scareText: 'The liquid in every glass boils. Voices rise from them — toasts, confessions, death rattles. One voice cuts through: "To your health. Or what\'s left of it." You drink without deciding to. It tastes like your own blood. The glasses refill.',
          sanityDamage: 28,
          duration: 4000,
        },
        items: ['crystal glass'],
        ambientDescription: 'The green flames cast shadows that don\'t match the furniture.',
      },
      coal_chute: {
        id: 'coal_chute',
        name: 'Coal Chute',
        description: 'A vertical shaft where coal was once dumped from outside. The chute is dark and narrow, but you can see stars at the top — or what look like stars. The coal at the bottom crunches underfoot, and some pieces are oddly shaped.',
        atmosphere: 'dread',
        exits: ['boiler_room'],
        hasKey: false,
        prank: {
          id: 'coal_hands',
          type: 'jumpscare',
          triggerText: 'You dig through the coal...',
          scareText: 'The coal pieces are petrified HANDS, curled into fists. As you uncover more, they uncurl, reaching upward. Hundreds of them, all reaching, all at once. The "stars" above blink in unison — they\'re not stars. They\'re eyes looking down at you.',
          sanityDamage: 32,
          duration: 3500,
        },
        items: ['lump of coal'],
        ambientDescription: 'The "stars" above blink in unison. The coal just moved underfoot.',
      },
      bone_chamber: {
        id: 'bone_chamber',
        name: 'Bone Chamber',
        description: 'The walls, floor, and ceiling are made entirely of arranged bones — femurs, ribs, skulls — all fitted together with impossible precision. It\'s architecture made of death, and it\'s beautiful in the worst way.',
        atmosphere: 'nightmare',
        exits: ['tunnel', 'ossuary_gate'],
        hasKey: true,
        prank: {
          id: 'bone_wall',
          type: 'creepy',
          triggerText: 'You trace the bone patterns on the wall...',
          scareText: 'The entire chamber REARRANGES. Walls rotate, bones click into new configurations. When it stops, the bones form words on every surface: "THANK YOU FOR ADDING YOURS." The floor shifts under you — the bones are rearranging to make a space shaped exactly like a human body. Your size.',
          sanityDamage: 35,
          duration: 4500,
        },
        items: ['carved femur'],
        ambientDescription: 'The bones click and settle. The chamber is getting smaller.',
      },
      generator_room: {
        id: 'generator_room',
        name: 'Generator Room',
        description: 'A diesel generator sits dead in the center. Fuel lines run along the ceiling like ivy. The fuel in the lines moves — not flowing, but PULSING, as if the mansion is the body and this is the heart.',
        atmosphere: 'terror',
        exits: ['maintenance_tunnel', 'fuse_box'],
        hasKey: true,
        prank: {
          id: 'generator_start',
          type: 'door_slam',
          triggerText: 'You try to start the generator...',
          scareText: 'It starts. The lights BLAZE. Every corner has something standing in it. Figures pressed against walls, faces in the pipes, eyes in the shadows. The generator roars. The lights strobe. The figures DANCE — and their dancing forms the shape of a ritual. Around you. You\'re the altar.',
          sanityDamage: 35,
          duration: 4500,
        },
        items: ['spark plug'],
        ambientDescription: 'The fuel in the lines pulses like blood. It\'s getting faster.',
      },
      crypt_main: {
        id: 'crypt_main',
        name: 'Main Crypt',
        description: 'Rows of stone sarcophagi stretch into darkness. Each lid is carved with a face — and every face is different, yet somehow familiar. One sarcophagus is open and empty. The lid lies beside it, its carved face now screaming.',
        atmosphere: 'nightmare',
        exits: ['crypt_entrance', 'catacombs'],
        hasKey: false,
        prank: {
          id: 'crypt_open',
          type: 'possession',
          triggerText: 'You look into the open sarcophagus...',
          scareText: 'It\'s not empty. Something was inside and now it\'s standing behind you. You feel breath on your neck and hands on your shoulders. "I\'ve been waiting for someone to check." You turn — nothing. But the lid is back on. The carved face is YOURS. And its expression is terror.',
          sanityDamage: 38,
          duration: 5000,
        },
        items: [],
        ambientDescription: 'The carved faces on the sarcophagi change expression when you blink.',
      },
      urn_hall: {
        id: 'urn_hall',
        name: 'Urn Hall',
        description: 'Hundreds of urns line shelves cut into the stone. Each has a name plate, but the names are constantly changing. The urns are warm, as if the ashes inside are still burning.',
        atmosphere: 'nightmare',
        exits: ['crypt_entrance'],
        hasKey: false,
        prank: {
          id: 'urn_names',
          type: 'illusion',
          triggerText: 'You read the name plates...',
          scareText: 'Every plate reads YOUR NAME. Hundreds of times. The urns rattle. Ashes pour out, forming your silhouette on the floor — lying down, at rest. The ashes begin to rise, forming a standing figure made of your cremated remains. It opens ash-eyes and reaches for you.',
          sanityDamage: 34,
          duration: 4500,
        },
        items: ['urn fragment'],
        ambientDescription: 'The name plates flicker with new text. One just showed YOUR name.',
      },
      ossuary_gate: {
        id: 'ossuary_gate',
        name: 'Ossuary Gate',
        description: 'A gate of rib bones leads to a lower level. Beyond it, you can see the cellar continuing into the mansion\'s deepest foundation. The gate has no lock — it simply requires the courage to pass through bones that may still be attached to something living.',
        atmosphere: 'nightmare',
        exits: ['bone_chamber', 'deep_well'],
        hasKey: false,
        prank: entryScare('ossuary_grab', 'The rib bones of the gate GRAB you as you pass through. They squeeze — not to trap, but to EMBRACE. You hear a heartbeat from inside the walls. The ribs are part of something enormous, and it just hugged you.', 28),
        items: [],
        ambientDescription: 'The ribs of the gate expand and contract, breathing.',
      },
      fuse_box: {
        id: 'fuse_box',
        name: 'Fuse Box',
        description: 'An ancient electrical panel with cloth-insulated wiring. Fuses are missing, and the remaining ones glow with a sickly amber light. Labels read: "NORTH WING," "EAST WING," "THEM," "US."',
        atmosphere: 'terror',
        exits: ['generator_room'],
        hasKey: true,
        prank: {
          id: 'fuse_pull',
          type: 'door_slam',
          triggerText: 'You pull the fuse labeled "THEM"...',
          scareText: 'The lights go out for three full seconds. When they return, you\'re in the same room — but reversed. Left is right. A new fuse box has appeared with a label: "YOU." It\'s already pulled. And from behind the new fuse box, a hand reaches out — your hand, attached to nothing.',
          sanityDamage: 30,
          duration: 4000,
        },
        items: ['fuse cartridge'],
        ambientDescription: 'The amber glow pulses. The "THEM" and "US" labels just swapped.',
      },
      catacombs: {
        id: 'catacombs',
        name: 'Catacombs',
        description: 'A vast underground network of tunnels with bones stacked floor to ceiling. The arrangement is methodical, almost artistic. Some bones have been carved with intricate patterns — eyes, mouths, spirals. The deeper you go, the fresher the bones appear.',
        atmosphere: 'nightmare',
        exits: ['crypt_main', 'well_room'],
        hasKey: true,
        prank: {
          id: 'catacomb_eyes',
          type: 'jumpscare',
          triggerText: 'You examine the carved eye patterns...',
          scareText: 'Every carved eye OPENS. Hundreds of bone eyes stare at you. They blink in sequence, forming words in Morse code. The mouths begin to move, producing a grinding sound. A wall-voice: "We see you. We always have. We are the walls. We are the floor. We have ALWAYS been here."',
          sanityDamage: 40,
          duration: 5000,
        },
        items: ['carved bone eye'],
        ambientDescription: 'The bone walls are warm, like living tissue. They pulse.',
        journalEntry: { id: 'journal_eleanor_5', title: "Eleanor's Notebook — Entry 5", text: "Day 14. The bone walls are warm. They pulse. I pressed my ear against them and heard breathing — then a voice: 'Welcome home.' I think the bones are previous visitors. I think I'm becoming the walls. I think that's the point.", chapter: 2 },
      },
      deep_well: {
        id: 'deep_well',
        name: 'The Deep Well',
        description: 'An ancient well in the lowest part of the cellar. The water is perfectly still and reflects the ceiling above — but the reflection shows a ceiling that doesn\'t match. In the water\'s reflection, you can see the attic above, not the cellar.',
        atmosphere: 'nightmare',
        exits: ['ossuary_gate'],
        hasKey: false,
        prank: {
          id: 'well_reflection',
          type: 'mirror',
          triggerText: 'You look into the well water...',
          scareText: 'The reflection shows you looking DOWN — which means the "you" in the water is looking UP. But it\'s not looking up from below. It\'s looking down from above. The water isn\'t a reflection — it\'s a window. And on the other side, you\'re already there, waving. Smiling. The well version of you reaches through the surface.',
          sanityDamage: 38,
          duration: 5500,
        },
        items: ['well water vial'],
        ambientDescription: 'The water is so still it doesn\'t ripple when you touch it. Something moved in it.',
      },
      well_room: {
        id: 'well_room',
        name: 'Well Chamber',
        description: 'A chamber with a stone well at its center. Unlike the deep well, this one has a bucket mechanism. The bucket descends, and when it returns, it holds not water but a small, folded note: "The way up is the way down." A ladder leads upward into darkness.',
        atmosphere: 'nightmare',
        exits: ['catacombs', 'attic_preview'],
        hasKey: false,
        prank: entryScare('well_bucket', 'The bucket rises on its own. Inside is a finger — still wearing your ring. You look at your hand. The ring is there. The finger in the bucket is wearing an identical ring. Whose finger is it?', 30),
        items: ['folded note'],
        ambientDescription: 'The bucket rises and falls on its own. It always has something new inside.',
      },
      attic_preview: {
        id: 'attic_preview',
        name: 'Upward Passage',
        description: 'The ladder leads to a trapdoor. Above, you hear the distinctive sound of a music box, playing faintly. The air from above is warm and dusty. This leads to the next level.',
        atmosphere: 'terror',
        exits: ['well_room'],
        hasKey: false,
        prank: entryScare('attic_music', 'The music box above changes tune. You recognize it — it\'s the lullaby from your childhood. But it\'s playing backward. And when played backward, the melody is a funeral dirge. Your funeral dirge.', 26),
        items: [],
        ambientDescription: 'The music box above winds and unwinds. It just changed key.',
      },
    },
  },
  {
    id: 3,
    name: 'The Attic of Whispers',
    subtitle: 'Where thoughts become voices',
    introNarrative: [
      'The music box plays a lullaby you almost recognize — from a dream you never had.',
      'Eleanor spent her last coherent hours up here, filling notebooks with the same sentence on every page: "IT LEARNS BY LISTENING."',
      'Every thought you have is overheard. Every fear you feel is catalogued. The attic is the mansion\'s ear.',
    ],
    exitNarrative: [
      'The impossible staircase folds reality into itself. You see the mirror dimension beyond.',
      'Eleanor\'s final notebook lies open on the stairs. One page remains: "I can see myself from every angle at once. I am beautiful. I am infinite. I am —"',
      'The sentence is incomplete. The pen is still in her hand. But she is not here.',
    ],
    startRoom: 'attic_landing',
    requiredKeys: 5,
    colorScheme: {
      primary: '#0a1a0a',
      accent: '#44ff44',
      bg: '#050a05',
      glow: '#44ff4440',
    },
    rooms: {
      attic_landing: {
        id: 'attic_landing',
        name: 'Attic Landing',
        description: 'A narrow staircase leads up to a low-ceilinged space. The air is thick with dust and the smell of old mothballs. Covered furniture creates a maze of shapes in the dimness. Something scratches inside the walls.',
        atmosphere: 'dread',
        exits: ['storage_room', 'doll_room', 'music_room', 'trunk_room'],
        hasKey: false,
        prank: entryScare('attic_whisper', 'A hundred voices whisper your name from inside the walls. Not in unison — in rounds, like a canon. The whispers overlap and layer until your name becomes an alien sound, meaningless, just noise. You\'ve lost the meaning of your own name.', 28),
        items: [],
        ambientDescription: 'The scratching inside the walls follows you. It keeps tempo with your heartbeat.',
      },
      storage_room: {
        id: 'storage_room',
        name: 'Storage Room',
        description: 'Piles of forgotten belongings are stacked to the ceiling. Old trunks, broken furniture, and boxes labeled with dates from decades ago. One box is labeled "DO NOT OPEN — EVER." It is open.',
        atmosphere: 'terror',
        exits: ['attic_landing', 'narrow_corridor', 'photo_studio'],
        hasKey: true,
        prank: {
          id: 'storage_box',
          type: 'jumpscare',
          triggerText: 'You look inside the opened box...',
          scareText: 'Inside is a perfect wax replica of your face. As you stare, it opens its eyes — YOUR eyes. It mouths words you can\'t hear. Then the wax MELTS, reforming into a screaming version of you, then back to calm, then screaming, alternating faster and faster until it EXPLODES, covering you in hot wax.',
          sanityDamage: 36,
          duration: 4000,
        },
        items: ['old music box'],
        ambientDescription: 'Something inside the walls is getting closer. It\'s right behind the plaster.',
      },
      doll_room: {
        id: 'doll_room',
        name: 'The Doll Room',
        description: 'Hundreds of dolls fill every surface — shelves, chairs, the floor. Porcelain, cloth, wood — all sizes, all staring in the same direction. Toward the door. Toward you. One doll in the center has no face.',
        atmosphere: 'terror',
        exits: ['attic_landing', 'porcelain_hall'],
        hasKey: true,
        prank: {
          id: 'doll_turn',
          type: 'possession',
          triggerText: 'You step into the room...',
          scareText: 'Every doll turns its head to face you simultaneously. The sound of hundreds of porcelain necks SNAPPING echoes through the room. The faceless doll raises its arm and points at you. Your arm raises too — without your consent. You are the doll now. You are ALL the dolls.',
          sanityDamage: 40,
          duration: 4500,
        },
        items: [],
        ambientDescription: 'The dolls blink when you aren\'t looking. Some just moved closer.',
      },
      music_room: {
        id: 'music_room',
        name: 'Music Room',
        description: 'An old piano sits in the center, its keys yellowed and some missing. A gramophone sits silent on a table. Sheet music is scattered everywhere, covered in frantic scribbling that replaces the notes.',
        atmosphere: 'dread',
        exits: ['attic_landing', 'secret_attic', 'conductor_study'],
        hasKey: true,
        prank: {
          id: 'piano_play',
          type: 'whisper',
          triggerText: 'You touch the piano keys...',
          scareText: 'The piano plays on its own — a melody you\'ve never heard but somehow KNOW. The gramophone crackles: a child sings "One by one, you\'ll come undone. Two by two, we\'ll come for you. Three by three, you\'ll never leave." Your fingers move to play along. You can\'t stop. The song is YOU.',
          sanityDamage: 35,
          duration: 5000,
        },
        items: ['sheet music'],
        ambientDescription: 'A music box plays from somewhere close. It just changed to YOUR song.',
        journalEntry: { id: 'journal_eleanor_6', title: "Eleanor's Notebook — Entry 6", text: "Day 16. The piano plays my thoughts. Not metaphorically — it converts my inner monologue into melody. When I'm afraid, the music is discordant. When I try to lie, it plays wrong notes. The attic is the house's ear, and it has perfect pitch.", chapter: 3 },
      },
      narrow_corridor: {
        id: 'narrow_corridor',
        name: 'Narrow Corridor',
        description: 'A corridor so narrow you must turn sideways. The walls are covered in children\'s drawings — houses, families, suns. But in each drawing, a black figure stands behind the family, growing larger with each picture.',
        atmosphere: 'terror',
        exits: ['storage_room'],
        hasKey: false,
        prank: {
          id: 'corridor_figure',
          type: 'shadow',
          triggerText: 'You examine the drawings more closely...',
          scareText: 'In the last drawing, the black figure has STEPPED OUT of the paper. Cold breath on your neck: "I\'ve been waiting for you to look at me." You turn — nothing. But ALL the drawings have changed. Every family is gone. Every drawing shows only the black figure. And it has YOUR face.',
          sanityDamage: 38,
          duration: 4500,
        },
        items: [],
        ambientDescription: 'The black figure in the drawings moves between frames. It just changed position.',
      },
      secret_attic: {
        id: 'secret_attic',
        name: 'The Secret Attic',
        description: 'Behind a loose panel, a room that shouldn\'t exist. The geometry is wrong — angles that don\'t add up, corners that bend inward. A single chair faces a wall covered in photographs of every room in the mansion. Each photo was taken from an impossible angle.',
        atmosphere: 'nightmare',
        exits: ['music_room', 'impossible_staircase'],
        hasKey: false,
        prank: {
          id: 'secret_photos',
          type: 'mirror',
          triggerText: 'You look at the photographs on the wall...',
          scareText: 'You find a photo of yourself — in this room — right now — taken from directly behind you. You spin — nothing. A NEW photo appears of you spinning. Another of you looking at the new photo. The camera is HERE. Photos multiply exponentially, covering the walls, the floor, the ceiling. All of you. All now.',
          sanityDamage: 45,
          duration: 5500,
        },
        items: ['impossible photograph'],
        ambientDescription: 'The angles of the room make you feel watched from every direction. New photos keep appearing.',
        journalEntry: { id: 'journal_eleanor_7', title: "Eleanor's Notebook — Entry 7", text: "Day 17. The impossible room. The angles don't add up. I've been here for what feels like hours, but the clock says it's been three days. The photographs on the wall multiply — they show me aging. I look older. Am I older? Is the house consuming my time?", chapter: 3 },
      },
      trunk_room: {
        id: 'trunk_room',
        name: 'Trunk Room',
        description: 'Dozens of trunks are stacked haphazardly. Some are locked, others burst open with clothes from different eras. One trunk breathes — its lid rising and falling rhythmically. A tag reads: "DO NOT RELEASE."',
        atmosphere: 'terror',
        exits: ['attic_landing'],
        hasKey: false,
        prank: {
          id: 'trunk_breathe',
          type: 'jumpscare',
          triggerText: 'You open the breathing trunk...',
          scareText: 'Inside is an entire room — fully furnished, with someone sitting in a chair reading. They look up, annoyed: "Close the lid. You\'re letting the weather in." The trunk slams from inside. Then ALL the trunks begin breathing. Their lids rise and fall. Something in each one is alive.',
          sanityDamage: 34,
          duration: 3500,
        },
        items: ['trunk key'],
        ambientDescription: 'The breathing trunk inhales and exhales. Other trunks have started too.',
      },
      photo_studio: {
        id: 'photo_studio',
        name: 'Photo Studio',
        description: 'An old photographer\'s studio with a cloth backdrop, standing lights, and a camera on a tripod. Development trays sit on a table, and photographs hang from lines — portraits of people whose expressions shift from stoic to terrified as they progress.',
        atmosphere: 'terror',
        exits: ['storage_room'],
        hasKey: true,
        prank: {
          id: 'photo_flash',
          type: 'illusion',
          triggerText: 'You look through the camera viewfinder...',
          scareText: 'Through the lens, a family poses before the backdrop, smiling. Their smiles grow wider — wider than faces allow. The camera FLASHES. When your vision clears, the family is standing AROUND you, still smiling. They close in. Their teeth are too numerous, their mouths too wide.',
          sanityDamage: 36,
          duration: 4500,
        },
        items: ['flash bulb'],
        ambientDescription: 'The camera shutter clicks on its own. Each click is closer together.',
      },
      porcelain_hall: {
        id: 'porcelain_hall',
        name: 'Porcelain Hall',
        description: 'A corridor where the walls are lined with porcelain masks instead of dolls. Each mask is a different expression — joy, rage, sorrow, terror. The masks are warm, and condensation forms inside them as if someone is breathing behind them.',
        atmosphere: 'nightmare',
        exits: ['doll_room', 'mask_chamber'],
        hasKey: false,
        prank: {
          id: 'mask_speak',
          type: 'possession',
          triggerText: 'You hold a mask to your ear...',
          scareText: 'The mask whispers: "Put me on. I want to see what you see." Your hands bring the mask to your face against your will. For one second, you see through its eyes — yourself, from the wall, surrounded by masks that are ALL alive. And they\'re all wearing you.',
          sanityDamage: 38,
          duration: 4500,
        },
        items: ['porcelain mask'],
        ambientDescription: 'The masks fog from within. They\'re all looking at you.',
      },
      conductor_study: {
        id: 'conductor_study',
        name: 'Conductor\'s Study',
        description: 'A desk covered in musical scores with impossible time signatures. A metronome ticks at a rate that makes your heartbeat try to match it. A conductor\'s baton lies across the desk, and it vibrates with every tick.',
        atmosphere: 'dread',
        exits: ['music_room'],
        hasKey: true,
        prank: {
          id: 'conductor_baton',
          type: 'possession',
          triggerText: 'You pick up the conductor\'s baton...',
          scareText: 'Your arm rises on its own, conducting an invisible orchestra. Sound fills the room from nowhere. Your body conducts a symphony you\'ve never learned. The crescendo builds — the orchestra is playing the sound of the mansion GRINDING, the walls moving, the house rearranging. You are its instrument.',
          sanityDamage: 35,
          duration: 5000,
        },
        items: ['baton'],
        ambientDescription: 'The metronome syncs with your heartbeat. It\'s speeding up.',
      },
      impossible_staircase: {
        id: 'impossible_staircase',
        name: 'Impossible Staircase',
        description: 'A staircase that Escher would weep at. Steps lead up and down simultaneously. Walking up brings you to the same floor. Walking down brings you to the same floor. The geometry folds in on itself. At the center, a door that wasn\'t there before shimmers.',
        atmosphere: 'nightmare',
        exits: ['secret_attic', 'mirror_preview'],
        hasKey: false,
        prank: {
          id: 'staircase_loop',
          type: 'illusion',
          triggerText: 'You try to climb the staircase...',
          scareText: 'You climb and climb and climb. The same stairs, over and over. You pass yourself going the other direction — then again — then TEN of you, a hundred. You\'ve been climbing for eternity. You stop. You\'re back where you started. But you\'re older. Your hair is grey. How long were you climbing?',
          sanityDamage: 42,
          duration: 5500,
        },
        items: [],
        ambientDescription: 'The stairs don\'t lead anywhere — they lead everywhere. Time is wrong here.',
      },
      mask_chamber: {
        id: 'mask_chamber',
        name: 'Mask Chamber',
        description: 'A circular room where porcelain masks hang from every surface — ceiling included. In the center, a mirror reflects the masks, but in the reflection, the masks are wearing faces — YOUR face, in every expression.',
        atmosphere: 'nightmare',
        exits: ['porcelain_hall'],
        hasKey: true,
        prank: {
          id: 'mask_your_face',
          type: 'mirror',
          triggerText: 'You look into the central mirror...',
          scareText: 'Every mask has your face. They speak at once: "We are you. Every version. Every possibility. The you that stayed. The you that died. The you that BECAME the mansion." The mirror cracks, and through the cracks, you see infinite mirrors, infinite yous — all screaming.',
          sanityDamage: 44,
          duration: 5500,
        },
        items: ['mirror shard mask'],
        ambientDescription: 'The masks rotate to track your movement. They all have your face now.',
      },
      mirror_preview: {
        id: 'mirror_preview',
        name: 'Shimmering Portal',
        description: 'The door from the impossible staircase leads to a space between spaces. The walls here are reflective — not mirrors, but surfaces that show other places. One reflection shows a corridor of mirrors. The next level awaits.',
        atmosphere: 'void',
        exits: ['impossible_staircase'],
        hasKey: false,
        prank: entryScare('mirror_door', 'You step through and catch a glimpse of yourself in every reflective surface — but every version of you is in a different room, at a different time. One of them is dead. One of them IS the mansion. They all wave.', 30),
        items: [],
        ambientDescription: 'Your reflections in the walls don\'t match your pose. They\'re all doing different things.',
      },
    },
  },
  {
    id: 4,
    name: 'The Mirror Dimension',
    subtitle: 'Where reflections have their own intentions',
    introNarrative: [
      'You step through the glass and the world inverts. You are the reflection now.',
      'Eleanor is here — or what remains of her. Her face appears in every surface, mouthing words you cannot hear.',
      'She is trying to warn you. Or she is trying to lure you. In the mirror world, the two are the same.',
    ],
    exitNarrative: [
      'The void threshold opens — a wound in reality where the mansion\'s heart beats.',
      'Eleanor\'s voice, clear for the first time, echoes from the other side: "I tried to burn it down. I poured gasoline on the walls. The walls drank it. They liked it."',
      '"The heart is at the center. Destroy it, and the house dies. But the house already knows you\'re coming. It has always known."',
    ],
    startRoom: 'mirror_hall',
    requiredKeys: 5,
    colorScheme: {
      primary: '#1a1a2e',
      accent: '#8888ff',
      bg: '#0a0a1e',
      glow: '#8888ff40',
    },
    rooms: {
      mirror_hall: {
        id: 'mirror_hall',
        name: 'Hall of Mirrors',
        description: 'A corridor of full-length mirrors on both sides. Your reflections stretch and distort as you walk. Some reflections seem a fraction of a second behind your movements. One reflection is missing entirely.',
        atmosphere: 'terror',
        exits: ['reflection_room', 'shattered_chamber', 'infinity_room', 'corridor_of_echoes'],
        hasKey: false,
        prank: entryScare('mirror_missing', 'You look for your missing reflection. You find it — in a different mirror, in a different POSE. It\'s been doing things without you. It turns to face you and mouths: "I don\'t need you anymore."', 32),
        items: [],
        ambientDescription: 'Your reflections move out of sync. One just did something you didn\'t do.',
      },
      reflection_room: {
        id: 'reflection_room',
        name: 'The Reflection Room',
        description: 'A room where every surface is mirrored — floor, ceiling, walls. You see infinite copies of yourself stretching in every direction. But in one of the distant reflections, a figure stands that isn\'t you.',
        atmosphere: 'nightmare',
        exits: ['mirror_hall', 'reverse_lounge'],
        hasKey: true,
        prank: {
          id: 'reflection_stranger',
          type: 'possession',
          triggerText: 'You try to focus on the non-you figure...',
          scareText: 'The figure is RIGHT BEHIND your reflection. It wears your clothes, your face — but WRONG. It smiles: "I\'m the real one now." Your reflection begins copying IT instead of you. You raise your hand — your reflection doesn\'t. IT raises its hand — your reflection copies. You\'ve been replaced in your own mirror.',
          sanityDamage: 42,
          duration: 5500,
        },
        items: ['mirror shard'],
        ambientDescription: 'In the infinite reflections, one always faces the wrong direction. It\'s getting closer.',
      },
      shattered_chamber: {
        id: 'shattered_chamber',
        name: 'Shattered Chamber',
        description: 'A single massive mirror dominates this room — completely shattered. Each fragment reflects a different scene, none of them matching the room you\'re standing in. One fragment shows your bedroom at home. Another shows a hospital room.',
        atmosphere: 'nightmare',
        exits: ['mirror_hall', 'beyond_mirror', 'glass_forest'],
        hasKey: true,
        prank: {
          id: 'shattered_scenes',
          type: 'creepy',
          triggerText: 'You peer into the fragment showing your bedroom...',
          scareText: 'In your bedroom, someone sleeps in your bed. They look just like you. They open their eyes, look directly at you through the shard, and smile. "Don\'t worry — I\'ll take good care of your life." Behind them, your family walks in. They greet the reflection, not you. They don\'t know you\'re gone.',
          sanityDamage: 40,
          duration: 5000,
        },
        items: [],
        ambientDescription: 'The fragments show scenes that change when you blink. One shows your funeral.',
        journalEntry: { id: 'journal_eleanor_8', title: "Eleanor's Notebook — Entry 8", text: "Day 18. I looked into a shard showing my bedroom at home. Someone is living my life. They wear my face. My family can't tell the difference. I don't think there IS a difference anymore. The reflection replaced me. Or I replaced it. I can't remember which side I'm on.", chapter: 4 },
      },
      infinity_room: {
        id: 'infinity_room',
        name: 'Infinity Room',
        description: 'Two mirrors face each other, creating an infinite corridor of reflections. But the reflections don\'t recede into infinity — they get darker, and at the very end, something is moving. Coming closer with each passing second.',
        atmosphere: 'nightmare',
        exits: ['mirror_hall', 'fracture_point'],
        hasKey: true,
        prank: {
          id: 'infinity_approach',
          type: 'jumpscare',
          triggerText: 'You lean closer to see what\'s approaching...',
          scareText: 'A face SLAMS against the glass from the far end — YOUR face, twisted in absolute terror, mouth open in a scream, eyes bleeding black. It pounds on the glass, cracking it. Your own voice from the other side: "DON\'T LET ME IN! DON\'T LET ME—" The glass SHATTERERS. For one second, it\'s in the room with you. Then the mirrors reform. It\'s back at the far end. Closer now.',
          sanityDamage: 45,
          duration: 3500,
        },
        items: ['reflection key'],
        ambientDescription: 'Something in the infinite corridor is getting closer. Much closer.',
      },
      beyond_mirror: {
        id: 'beyond_mirror',
        name: 'Beyond the Mirror',
        description: 'You\'ve stepped through. This is the mirror world — everything is reversed. Left is right, text reads backward. But the mansion here is alive. The walls pulse. The floor breathes. And there are no mirrors here — because you ARE the reflection now.',
        atmosphere: 'void',
        exits: ['shattered_chamber', 'mirror_garden', 'reverse_kitchen'],
        hasKey: true,
        prank: {
          id: 'mirror_world',
          type: 'possession',
          triggerText: 'You look at your hands in the mirror world...',
          scareText: 'Your hands are becoming translucent. You\'re FADING. The mirror world absorbs you, replacing you with the thing that wears your face. You can feel your memories being overwritten — you remember living IN the mirror, always, and someone else living YOUR life. You can\'t remember which memories are real anymore.',
          sanityDamage: 48,
          duration: 5500,
        },
        items: ['reversal talisman'],
        ambientDescription: 'You can feel the mirror world trying to make you permanent. Your edges are blurring.',
      },
      corridor_of_echoes: {
        id: 'corridor_of_echoes',
        name: 'Corridor of Echoes',
        description: 'Every sound you make echoes back — but the echoes say different words. Your footsteps echo as whispers. Your whispers echo as screams. At the end of the corridor, a mirror shows you saying things you never said.',
        atmosphere: 'terror',
        exits: ['mirror_hall', 'echo_chamber'],
        hasKey: false,
        prank: {
          id: 'echo_lies',
          type: 'whisper',
          triggerText: 'You speak aloud to test the echoes...',
          scareText: 'You say "Hello." The echo says "Help me." You say "Where am I?" The echo says "She\'s behind you." Breath on your neck. A voice — not an echo: "Finally. Someone who listens." Hands grip your shoulders. Teeth graze your ear. "I have so much to tell you. So much you\'ll forget."',
          sanityDamage: 35,
          duration: 4500,
        },
        items: [],
        ambientDescription: 'The echoes speak in a voice that isn\'t quite yours. It knows things you don\'t.',
      },
      reverse_lounge: {
        id: 'reverse_lounge',
        name: 'Reversed Lounge',
        description: 'A comfortable sitting room — but everything is backwards. The clock runs counter-clockwise, the fireplace sucks heat from the room, books have their text reversed. The furniture is arranged for a gathering, but the chairs face away from each other.',
        atmosphere: 'nightmare',
        exits: ['reflection_room'],
        hasKey: false,
        prank: {
          id: 'reverse_sit',
          type: 'illusion',
          triggerText: 'You sit in one of the chairs...',
          scareText: 'An invisible weight sits beside you. A hand rests on your arm. A voice: "Don\'t get comfortable — you\'re only visiting." The chair tips backward. You fall — but don\'t hit the floor. You float in a room that\'s now right-side up. Everything was always upside down. YOU were always upside down.',
          sanityDamage: 38,
          duration: 5000,
        },
        items: ['upside-down book'],
        ambientDescription: 'The clock ticks backwards. Each tick removes a second from your life.',
      },
      glass_forest: {
        id: 'glass_forest',
        name: 'Glass Forest',
        description: 'Shattered mirror fragments stand upright like trees in a forest of glass. Walking between them creates a thousand fractured reflections — each one a slightly different version of you, from different choices, different fates.',
        atmosphere: 'nightmare',
        exits: ['shattered_chamber', 'crystal_cave'],
        hasKey: false,
        prank: {
          id: 'glass_self',
          type: 'mirror',
          triggerText: 'You reach out to touch a glass fragment...',
          scareText: 'Your reflection reaches back. Its fingers EMERGE from the glass. It grabs your hand — cold, glassy skin. It pulls you toward the fragment, and for one moment, you switch places. You\'re in the glass, looking out at yourself, who smiles and walks away. Then you snap back. But which one are you now?',
          sanityDamage: 42,
          duration: 5500,
        },
        items: ['glass splinter'],
        ambientDescription: 'Each fragment shows a you that made a different choice. Some of them are screaming.',
      },
      fracture_point: {
        id: 'fracture_point',
        name: 'The Fracture Point',
        description: 'A room where reality itself has cracked. Lines of light split the air like broken glass suspended in space. Through the fractures, you glimpse other rooms, other levels, other yous — all experiencing the mansion simultaneously.',
        atmosphere: 'void',
        exits: ['infinity_room', 'between_worlds'],
        hasKey: true,
        prank: {
          id: 'fracture_see',
          type: 'illusion',
          triggerText: 'You peer through the fractures in reality...',
          scareText: 'You see every version of you that has entered this mansion. Some are in the cellar. Some in the attic. Some already gone. One looks back at you and mouths: "Don\'t advance. It gets worse. It gets so much—" Then something pulls them away. Through a different fracture, you see what pulled them. It sees you now too.',
          sanityDamage: 42,
          duration: 5000,
        },
        items: ['fracture fragment'],
        ambientDescription: 'The fractures hum with displaced time. You hear yourself screaming from the other side.',
      },
      mirror_garden: {
        id: 'mirror_garden',
        name: 'Mirror Garden',
        description: 'An impossible outdoor garden reflected in mirrors. In the real space, dead vines and withered trees. In the reflections, lush impossible flowers bloom — flowers with teeth, flowers with eyes, flowers that turn to watch you pass.',
        atmosphere: 'nightmare',
        exits: ['beyond_mirror', 'pool_of_truth'],
        hasKey: false,
        prank: {
          id: 'garden_bloom',
          type: 'possession',
          triggerText: 'You reach for a flower in the reflection...',
          scareText: 'The flower\'s eye blinks. Every flower turns to face you. Their petals open like mouths and begin to hum — a chord that resonates in your BONES. Vines in the real space wrap around your ankles, your wrists, your throat. The reflected flowers lean in to taste you. They\'re hungry. They\'ve been waiting.',
          sanityDamage: 38,
          duration: 4500,
        },
        items: ['eye blossom'],
        ambientDescription: 'The reflected flowers sway toward you like you\'re sunlight. They\'re getting closer.',
      },
      reverse_kitchen: {
        id: 'reverse_kitchen',
        name: 'Reversed Kitchen',
        description: 'Everything is backward — the stove freezes, the fridge is hot. Food on the counter is half-eaten as if someone was interrupted mid-meal. The sink drains upward. A mirror over the stove shows the kitchen right-side up, with someone cooking.',
        atmosphere: 'nightmare',
        exits: ['beyond_mirror'],
        hasKey: true,
        prank: {
          id: 'reverse_cook',
          type: 'possession',
          triggerText: 'You open the fridge...',
          scareText: 'Inside the hot fridge is a dinner plate with a photo of you — alive, from earlier tonight. Someone is cooking your timeline. The mirror over the stove shows the chef: you, but older, wearing a different face. It serves a plate of your own memories. You taste them. They taste like fear and loss.',
          sanityDamage: 40,
          duration: 5000,
        },
        items: ['frozen flame'],
        ambientDescription: 'The fridge hums with warmth. The stove radiates cold. Something is cooking.',
      },
      echo_chamber: {
        id: 'echo_chamber',
        name: 'Echo Chamber',
        description: 'A spherical room with perfect acoustics. Your heartbeat is amplified a thousand times, shaking the room. Your thoughts seem to echo — you can hear yourself thinking, but with a delay, and the echoes think different things.',
        atmosphere: 'void',
        exits: ['corridor_of_echoes'],
        hasKey: false,
        prank: {
          id: 'echo_think',
          type: 'possession',
          triggerText: 'You try to clear your mind...',
          scareText: 'In the silence, your thoughts echo back — but they\'re not yours. "I want to stay here forever." "I love this mansion." "I was always meant to be here." Your own voice, saying things you don\'t believe — yet. The longer you listen, the more true they feel. You\'re starting to agree with yourself.',
          sanityDamage: 40,
          duration: 5500,
        },
        items: ['sound crystal'],
        ambientDescription: 'Your thoughts echo. The echoes disagree with you. They\'re winning the argument.',
      },
      crystal_cave: {
        id: 'crystal_cave',
        name: 'Crystal Cave',
        description: 'Crystals grow from every surface, each one a perfect mirror. Light refracts into a thousand beams, each carrying an image. Some show the past, some the present. A few show things that haven\'t happened yet.',
        atmosphere: 'nightmare',
        exits: ['glass_forest', 'void_preview'],
        hasKey: true,
        prank: {
          id: 'crystal_future',
          type: 'illusion',
          triggerText: 'You look into a crystal showing the future...',
          scareText: 'You see yourself — older, broken, sitting in the Heart of the Mansion. You\'re smiling. The mansion has won. Another crystal: you leaving. Another: you dead. Another: you AS the mansion. Every future ends here. Every timeline converges. You were always coming here. You will always be here.',
          sanityDamage: 45,
          duration: 5500,
        },
        items: ['future crystal'],
        ambientDescription: 'The crystals show what was, what is, and what cannot be avoided.',
      },
      pool_of_truth: {
        id: 'pool_of_truth',
        name: 'Pool of Truth',
        description: 'A still pool on the mirror garden\'s floor. The water reflects perfectly, but shows the truth of things. Your reflection doesn\'t look like you think you look — it looks like what you really are, underneath.',
        atmosphere: 'void',
        exits: ['mirror_garden'],
        hasKey: false,
        prank: {
          id: 'pool_self',
          type: 'mirror',
          triggerText: 'You look at your true reflection...',
          scareText: 'Your reflection isn\'t human. It\'s the mansion. Walls where skin should be, doors for eyes, rooms for organs. You ARE the house. You have always been the house. The pool ripples, and the reflection reaches up to pull you under. You go willingly. The water tastes like home.',
          sanityDamage: 50,
          duration: 6000,
        },
        items: ['pool water'],
        ambientDescription: 'Your reflection shows something that doesn\'t look like you. It looks like home.',
        journalEntry: { id: 'journal_eleanor_9', title: "Eleanor's Notebook — Entry 9", text: "Day 19. The pool showed me what I really am: architecture. Walls and doors and rooms. I AM the house. I have always been the house. The person named Eleanor Voss was just a room the house built to hold a consciousness. I am not trapped in here. I AM here.", chapter: 4 },
      },
      between_worlds: {
        id: 'between_worlds',
        name: 'Between Worlds',
        description: 'A space between the mirror dimension and the mansion\'s heart. The floor is translucent — you can see the mansion below, and above, the mirror world. You stand in the membrane between reality and reflection. A door ahead pulses with a heartbeat.',
        atmosphere: 'void',
        exits: ['fracture_point'],
        hasKey: false,
        prank: entryScare('between_crush', 'The membrane squeezes. The mirror world above and the mansion below press together, and you\'re between them. For a moment, you exist in both places at once — reflected and real, observer and observed. You don\'t know which one you are anymore.', 35),
        items: [],
        ambientDescription: 'You are the barrier. The mansion pushes; the mirror pulls. You\'re getting thin.',
      },
      void_preview: {
        id: 'void_preview',
        name: 'The Void Threshold',
        description: 'The crystal cave narrows into a passage where light itself bends. Ahead, darkness — not the absence of light, but something more fundamental. An un-being. This leads to the mansion\'s heart. The final level.',
        atmosphere: 'void',
        exits: ['crystal_cave'],
        hasKey: false,
        prank: entryScare('void_call', 'The void calls your name. Not with sound — with absence. The absence of your name in the universe is what calls you. It removes you from everywhere else to summon you here. You feel yourself disappearing from the memories of everyone who ever knew you.', 38),
        items: [],
        ambientDescription: 'The darkness ahead is not dark. It is nothing. And it knows you.',
      },
    },
  },
  {
    id: 5,
    name: 'The Heart of the Mansion',
    subtitle: 'Where it has always been waiting',
    introNarrative: [
      'This is the place the mansion has been building toward since before you were born.',
      'Eleanor is not here. She IS here — she is the walls, the floor, the heartbeat. She was absorbed 17 days ago.',
      'The heart is the core. The source. The original crime. Destroy it, and every soul trapped in these walls goes free — including yours.',
    ],
    exitNarrative: [
      'The heart shatters. The mansion screams — not in pain, but in recognition.',
      'It finally understands what it always was: not a house, but a hunger that learned to build walls.',
      'As the walls dissolve, you see them — Eleanor, the officer, the three who vanished — standing in the light. Free. They do not look at you. They are already gone.',
    ],
    startRoom: 'void_entrance',
    requiredKeys: 5,
    colorScheme: {
      primary: '#0a0a0a',
      accent: '#ff0000',
      bg: '#000000',
      glow: '#ff000040',
    },
    rooms: {
      void_entrance: {
        id: 'void_entrance',
        name: 'The Void Entrance',
        description: 'The walls of the mansion have fallen away, revealing nothing — not darkness, but nothing. An absence of existence. You stand on the last fragment of floor, floating in void. Ahead, a structure of impossible geometry pulses like a heart.',
        atmosphere: 'void',
        exits: ['the_threshold', 'memory_hall', 'final_corridor', 'echoing_dark'],
        hasKey: false,
        prank: entryScare('void_aware', 'The void is AWARE of you. Not watching — BEING you. It occupies the same space as your consciousness. You think your thoughts, but they\'re also its thoughts. You can\'t tell where you end and it begins. It likes being you. It doesn\'t want to leave.', 40),
        items: [],
        ambientDescription: 'The void breathes. Inhale. Exhale. You breathe with it. You ARE it.',
      },
      the_threshold: {
        id: 'the_threshold',
        name: 'The Threshold',
        description: 'A doorway that shouldn\'t exist — it\'s a wound in reality itself. The edges of the door bleed light that casts shadows in the wrong direction. Through it, you can see every room of the mansion simultaneously, as if they are all the same room viewed from different angles.',
        atmosphere: 'void',
        exits: ['void_entrance', 'convergence'],
        hasKey: true,
        prank: {
          id: 'threshold_echo',
          type: 'possession',
          triggerText: 'You step through the threshold...',
          scareText: 'You are in EVERY room at once. Every prank, every scare, every horror — all happening simultaneously. The foyer ghost, the cellar hands, the dolls, the mirrors — ALL AT ONCE, ALL REAL, ALL NOW. You experience every terror the mansion has ever inflicted, all in one eternal moment.',
          sanityDamage: 50,
          duration: 5500,
        },
        items: ['threshold key'],
        ambientDescription: 'Time doesn\'t flow here. It pools. You\'re drowning in it.',
      },
      memory_hall: {
        id: 'memory_hall',
        name: 'Hall of Memories',
        description: 'A corridor lined with your own memories, projected on the walls like films. Your childhood. Your home. Your family. But in each memory, a dark figure stands in the background, growing larger, until in the final memories, it has replaced everyone you know.',
        atmosphere: 'void',
        exits: ['void_entrance', 'nameless_room'],
        hasKey: true,
        prank: {
          id: 'memory_replace',
          type: 'possession',
          triggerText: 'You watch your memories play out...',
          scareText: 'In the final memory, the dark figure turns to you. It\'s wearing your face. It reaches through the memory, through the wall, and grabs your wrist. Its touch is colder than death. "These were never YOUR memories. They were mine. I just let you borrow them." Every memory shifts — you\'re not in any of them. You never were.',
          sanityDamage: 55,
          duration: 6000,
        },
        items: [],
        ambientDescription: 'Your memories play on loop, each time slightly altered. You\'re disappearing from them.',
      },
      final_corridor: {
        id: 'final_corridor',
        name: 'The Final Corridor',
        description: 'A corridor of absolute darkness, lit only by the glow of your own beating heart, visible through your chest. At the end, a door — the last door. Beyond it, the mansion\'s heart beats in counterpoint to your own, growing louder as you approach.',
        atmosphere: 'void',
        exits: ['void_entrance', 'heart_room', 'the_pact'],
        hasKey: true,
        prank: {
          id: 'final_heartbeat',
          type: 'possession',
          triggerText: 'You walk toward the last door...',
          scareText: 'Your heartbeat and the mansion\'s synchronize. You feel its chambers as your own. You are not in the mansion — the mansion is in you. It always has been. The door isn\'t a door — it\'s a mirror. And in it, you see the mansion looking back, wearing your face, walking away into the world. You\'re not escaping. You\'re being released. INTO the world.',
          sanityDamage: 55,
          duration: 6500,
        },
        items: [],
        ambientDescription: 'Your heartbeat is not your own anymore. It has its own agenda.',
      },
      echoing_dark: {
        id: 'echoing_dark',
        name: 'Echoing Dark',
        description: 'An expanse of nothing that somehow produces sound. Every sound ever made in the mansion echoes here simultaneously — whispers, screams, laughter, the creak of stairs, the slam of doors. A cacophony of the mansion\'s history.',
        atmosphere: 'void',
        exits: ['void_entrance', 'silent_room'],
        hasKey: false,
        prank: {
          id: 'echoing_all',
          type: 'whisper',
          triggerText: 'You listen to the echoes...',
          scareText: 'Among the cacophony, you hear your own voice — from the future. You hear yourself screaming. You hear yourself laugh. You hear yourself say "I accept." The echoes converge into one word, spoken by every voice the mansion has ever consumed: "STAY." Your mouth forms the word. You almost say it.',
          sanityDamage: 45,
          duration: 5500,
        },
        items: ['echo in a bottle'],
        ambientDescription: 'All the mansion\'s voices speak at once. They\'re learning to speak as one.',
      },
      convergence: {
        id: 'convergence',
        name: 'The Convergence',
        description: 'All the mansion\'s rooms overlap here. The foyer\'s chandelier hangs in the cellar\'s boiler. The attic\'s dolls sit on the crypt\'s sarcophagi. Everything is one room now. And in the center, a key made of condensed nightmare.',
        atmosphere: 'void',
        exits: ['the_threshold'],
        hasKey: true,
        prank: {
          id: 'convergence_all',
          type: 'possession',
          triggerText: 'You reach for the key...',
          scareText: 'As your fingers close around it, every room you\'ve visited FLASHES before your eyes — not as memories, but as if you\'re STILL in all of them. Every prank triggers again, simultaneously. You experience the entire mansion again in one eternal second. You don\'t know which room you\'re in. You\'re in ALL of them. Forever.',
          sanityDamage: 50,
          duration: 6000,
        },
        items: ['nightmare key'],
        ambientDescription: 'All rooms are one room. All time is one moment. You exist everywhere at once.',
      },
      nameless_room: {
        id: 'nameless_room',
        name: 'The Nameless Room',
        description: 'A room with no name because names have no meaning here. The walls are covered in every language you\'ve ever spoken, and some you haven\'t. All the words say the same thing, and if you read them, you\'ll understand. Understanding is the danger.',
        atmosphere: 'void',
        exits: ['memory_hall', 'the_bloom'],
        hasKey: false,
        prank: {
          id: 'nameless_read',
          type: 'possession',
          triggerText: 'You read the words on the walls...',
          scareText: 'You understand. "You built this mansion. Every fear, every dark thought, every midnight dread — you laid the bricks. The mansion is not haunted. You ARE the haunting." The understanding rewrites you. You remember building the walls. You remember laying the foundation. You remember being the architect of your own prison. You always knew.',
          sanityDamage: 55,
          duration: 6500,
        },
        items: ['nameless scroll'],
        ambientDescription: 'The words rearrange to stay just barely unreadable. They want you to read them.',
      },
      the_pact: {
        id: 'the_pact',
        name: 'The Pact',
        description: 'A room with a stone altar and a contract written in black flame. The contract offers a deal: stay, and become the mansion. Leave, and the mansion comes with you. There is no option where the mansion releases you. The flame burns with your signature already on it.',
        atmosphere: 'void',
        exits: ['final_corridor'],
        hasKey: true,
        prank: {
          id: 'pact_sign',
          type: 'possession',
          triggerText: 'You read the contract...',
          scareText: 'The contract is already signed in your handwriting. You don\'t remember signing it. But as you read, you DO remember — you signed it before you were born. You signed it with your first breath. The mansion has always owned you. The "pranks" were the mansion playing with its food. You were never the player. You were always the game.',
          sanityDamage: 58,
          duration: 6500,
        },
        items: ['pact fragment'],
        ambientDescription: 'Your signature burns on the contract, written before your birth. The flame knows you.',
      },
      silent_room: {
        id: 'silent_room',
        name: 'The Silent Room',
        description: 'Absolute silence. Not quiet — SILENCE. The absence of sound as a physical force. You cannot hear your heartbeat, your breath, your thoughts. The silence presses against you, filling your ears, your mind, replacing thought with nothing.',
        atmosphere: 'void',
        exits: ['echoing_dark', 'the_core'],
        hasKey: false,
        prank: {
          id: 'silent_thought',
          type: 'possession',
          triggerText: 'You try to speak...',
          scareText: 'No sound. Silence consumes your words before they form. Your inner voice fades. You can\'t think. The silence is inside you now — eating your thoughts, your identity, your self. You try to remember your name. The silence swallows it. You try to remember your face. Gone. You are becoming the silence.',
          sanityDamage: 50,
          duration: 6500,
        },
        items: ['silence jar'],
        ambientDescription: 'The silence is a presence, not an absence. It\'s growing inside you.',
      },
      the_bloom: {
        id: 'the_bloom',
        name: 'The Bloom',
        description: 'In the heart of the nameless, something grows. A flower made of darkness, its petals negative images of light. It grows from a crack in nothing, fed by fear. It\'s beautiful. It\'s wrong. And it has your eyes at its center.',
        atmosphere: 'void',
        exits: ['nameless_room'],
        hasKey: false,
        prank: {
          id: 'bloom_stare',
          type: 'possession',
          triggerText: 'You gaze into the bloom\'s eyes...',
          scareText: 'Your eyes meet. The bloom sees you — every version, every dark corner of your soul. And it LIKES what it sees. It blooms wider — more petals, more eyes, all yours, all watching. A voice like roots breaking soil: "Stay. Grow with me. Become the garden. Become the house. Become." Your roots are already in the floor.',
          sanityDamage: 48,
          duration: 5500,
        },
        items: ['dark petal'],
        ambientDescription: 'The bloom grows with every moment. Its roots are under your feet.',
      },
      the_core: {
        id: 'the_core',
        name: 'The Core',
        description: 'The deepest point of silence. A spherical chamber where even thought ceases. In the center, a point of light — the only light in the void — burns with the heat of compressed sanity. It\'s the mansion\'s opposite. It\'s the way out. But reaching it means passing through yourself.',
        atmosphere: 'void',
        exits: ['silent_room'],
        hasKey: true,
        prank: {
          id: 'core_self',
          type: 'mirror',
          triggerText: 'You approach the point of light...',
          scareText: 'Between you and the light stands yourself — the real you, from before the mansion, untouched by fear. It looks at what you\'ve become and WEEPS. "Look what it did to you. Look what you let it do." It steps aside. The light is yours — if you can bear to see what you really are. You can\'t. You\'re horrifying.',
          sanityDamage: 42,
          duration: 5500,
        },
        items: ['core fragment'],
        ambientDescription: 'The light burns with the weight of every choice you\'ve made. It\'s blinding.',
      },
      heart_room: {
        id: 'heart_room',
        name: 'The Heart of the Mansion',
        description: 'The final room. A massive chamber where the mansion\'s true nature is revealed. At its center, a pulsating heart — part organic, part architectural — beats within a cage of ribs and support beams. The walls are alive. The floor is alive. And it has been waiting for you. Always.',
        atmosphere: 'void',
        exits: ['final_corridor'],
        hasKey: true,
        prank: entryScare('heart_beat', 'The heart BEATS and your chest echoes it. Your ribs align with its cage. Your blood pulses in sync. You are not visiting the heart — you are REUNITING with it. The separation was the illusion. The heart beats. You beat. The mansion beats. One pulse. One body. Yours.', 45),
        items: ['heart of the mansion'],
        ambientDescription: 'It beats. It waits. It knows. You are it.',
        journalEntry: { id: 'journal_eleanor_10', title: "Eleanor's Notebook — Final Entry", text: "Day 20. The heart beats. My chest echoes it. We are synchronized now. If you're reading this, you've come far enough to understand: the mansion doesn't trap people. It RECRUITS them. Every room is a conversion. Every scare is a test. You're not escaping — you're being prepared. But there's still time. The heart can be destroyed. I couldn't do it. I was already part of the walls by the time I understood. You still have your own skin. Use it. Burn it down.", chapter: 5 },
      },
    },
  },
];
